enabled: true

review:
  languages: [ "kotlin", "java" ]
  review_scope: "diff-only"          # options: full, diff-only, project
  max_comments: 15
  poem: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "Review the pull request title and suggest improvements if it’s unclear, lacks context, or doesn’t follow our naming convention."

tone: "constructive"            # options: friendly, professional, direct, constructive


instructions:
  - "If a new REST endpoint is created, verify there's a corresponding test case."
  - "Warn about any controller method that lacks input validation or exception handling."
  - "Check for usage of our structured logger (LoggerFactory.getLogger())."
  - "Flag any logging of passwords or access tokens."
  - "Ensure all public models used in REST responses have documentation comments."


rules:
  - no_hardcoded_secrets
  - avoid_plain_password_logging
  - enforce_test_coverage